# Generated by Django 5.0.6 on 2024-05-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_student_college_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
